version: '2'
services:
    bp250-app:
        image: bp250
        external_links:
            - bp250-postgresql:postgresql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresql:5432/bp250
        ports:
            - 8080:8080
    bp250-postgresql:
        extends:
            file: postgresql.yml
            service: bp250-postgresql
